name: mpcite_py3
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py37_1
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=hf484d3e_0
  - openssl=1.0.2p=h14c3975_0
  - pip=10.0.1=py37_0
  - python=3.7.0=hc3d631a_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.2.0=py37_0
  - sqlite=3.24.0=h84994c4_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.31.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - chardet==3.0.4
    - click==7.0
    - flask==1.0.2
    - idna==2.7
    - itsdangerous==0.24
    - jinja2==2.10
    - markupsafe==1.0
    - mongogrant==0.2.1
    - pymongo==3.7.1
    - requests==2.19.1
    - urllib3==1.23
    - werkzeug==0.14.1
    - "--editable=git+https://github.com/materialsproject/maggma.git#egg=maggma"
prefix: /home/huck/miniconda3/envs/mpcite_py3

